name: CLA note
description: Note on CLA automatic agreement
body:
  - type: markdown
    attributes:
      value: |
        By creating a PR or an issue you automatically argee to the CLA.
        See CONTRIBUTING.md
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
